### ISSUE TITLE
Section 19-4 Question

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#1020]
In section 19-4 RDS, the [logic ](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-4.md?plain=1#L51)says to take a `cooling_design_day_sequence` from a `multiplier_sch`.

We do not see this data under the Schedule object. Is it a new data that will release in the next schema version?

Also, I assume the `design_cooling_multiplier_schedule` is a 24 hour schedule since it is used for design day. Could you confirm?

**Comment by mkarpman** [comment]
Yes, this will be part of schema update, as discussed here https://github.com/open229/ruleset-model-description-schema/issues/150. @JasonGlazer can you provide more detailes?

**Comment by weilixu** [comment]
> Yes, this will be part of schema update, as discussed here [open229/ruleset-model-description-schema#150](https://github.com/open229/ruleset-model-description-schema/issues/150). @JasonGlazer can you provide more detailes?

Sounds good. Thank you Maria.

**Comment by claperle** [comment]
I think this is all set. This is where we left off. It just needs to be
added to the schema.

[image: image.png]

*Christina LaPerle (she/her)* PE, BEMP, CEM, CBCP
Senior Energy Engineer, Associate
________________
[image: image.png]
Phone 860.266.6220
We are always looking for motivated professionals to join our team. See our
career options here <https://karpmanconsulting.net/available-careers>!

**Comment by weilixu** [comment]
Thank you for the inputs. I am closing this issue since it will be addressed in the upcoming schema update.

**Comment by weilixu** [comment]
@yunjoonjung-PNNL 
The schema is updated, the data shall be: 
https://github.com/open229/ruleset-model-description-schema/blob/main/docs229/ASHRAE229.schema.json#L1505
