### ISSUE TITLE
get_fan_system_object_supply_return_exhaust_relief_total_kW_CFM_test function issue

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#1038]
The ruleset team discussed two points for the ```get_fan_system_object_supply_return_exhaust_relief_total_kW_CFM``` function (Please also refer to #1028).

1. **function name**: We suggest not including explicit units in the function name. The recommended new function name is ```get_fan_system_object_supply_return_exhaust_relief_total_power_flow``` or ```get_fan_system_object_info``` (We prefer the second name). The current name doesn't help the caller understand what is being retrieved.

2. **returned dict**:  Returning ```[supply fan power kW, return fan power kW, exhaust fan power kW, relief fan power kW]``` as a list is going to lead to all sorts of confusion and bugs going forward. We suggest each piece of information returned should be named so we don't get confused. The currently proposed implementation is shown [HERE](https://github.com/pnnl/ruleset-checking-tool/blob/6944f053574df3bbbf3c7c1d00d4fc62e909ede5/rct229/rulesets/ashrae9012019/ruleset_functions/get_fan_system_object_supply_return_exhaust_relief_total_kW_CFM.py#LL56C9-L63C10).

Could you check the two points make sense? If so, could you also reflect the updates to all the related RDS?

**Comment by yunjoonjung-PNNL** [comment]
1. Thank you. I'd appreciate it if you could let us know too.
2. This function is used in Rules 19-13, 14, 17, 20, and 23.

**Comment by mkarpman** [comment]
My vote is for the first name get_fan_system_object_supply_return_exhaust_relief_total_power_flow. I also don't mind the existing name. The "get_fan_system_object_info" option seems too generic - it's unclear what exactly is being returned as fan system object have many elements and attributes.

**Comment by yunjoonjung-PNNL** [comment]
Good point! After @claperle and other team members confirm, I'll update the name.

**Comment by claperle** [comment]
@yunjoonjung-PNNL I agree with Maria's comment.

**Comment by yunjoonjung-PNNL** [comment]
It looks great to me. I appreciate this update!
