### ISSUE TITLE
`get_zone_supply_return_exhaust_relief_terminal_fan_power_dict` function return dict type

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#1046]
In terms of the ```get_zone_supply_return_exhaust_relief_terminal_fan_power_dict``` function's [return dict](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/get_zone_supply_return_exhaust_relief_terminal_fan_power_dict.md#:~:text=zone_supply_return_exhaust_relief_terminal_fan_power_dict%5Bzone.id%5D%20%3D%20%5Bzone_total_supply_fan_power%2Czone_total_return_fan_power%2Czone_total_exhaust_fan_power%2Czone_total_relief_fan_power%2Czone_total_terminal_fan_power%5D), How about we return dict of dict instead of dict of list? 

The reason is returning ```[zone_total_supply_fan_power,zone_total_return_fan_power,zone_total_exhaust_fan_power,zone_total_relief_fan_power,zone_total_terminal_fan_power]``` list is going to lead to all sorts of confusion and bugs going forward. I'd like to suggest dict of dict type, as shown below.

One example would be 
```python
{
"zone_id_1": {
              "zone_supply_fan_power": 100,
              "zone_total_return_fan_power": 80,
              "zone_total_exhaust_fan_power": 60,
              "zone_total_relief_fan_power": 60,
              "zone_total_terminal_fan_power": 300,
              }
}
```

**Comment by yunjoonjung-PNNL** [comment]
Thank you! As far as I know, the rules you mentioned are all.

**Comment by weilixu** [comment]
Done implementation, close issue
