### ISSUE TITLE
Rule 19-19 RDS 

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#1075]
In [Rule 19-19 RDS,](https://github.com/pnnl/ruleset-checking-tool/blob/1227246071b15f9eeb996e5b929989d31d57026a/docs/section19/Rule19-19.md) , I believe Case 2 and 3 should be checked. The reason is 
i) ```AHJ_RA_compare``` comes out of nowhere.
ii) Other than ```AHJ_RA_compare```, the two cases are the same so, pass/fail logic is unclear.

Could you look into this?

**Comment by supriyagoel** [comment]
@yunjoonjung-PNNL when you say case 2 and 3 should be checked, do you mean in terms of adding additional rule tests for those 2 cases or do you mean adding the rule definition logic for the AHJ compare?

**Comment by yunjoonjung-PNNL** [comment]
After we discussed this, we decided to remove Case 2 and add the string message adding "conservative outcomes".
