### ISSUE TITLE
Rule 19-35 RDS Question

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#1078]
In [Rule 19-35 RDS](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-35.md), the ```OA_flow_schedule_match``` variable isn't used after comparing the baseline/proposed schedules. Could you check whether the ```OA_flow_schedule_match``` variable needs to be included in the rule assertion?

**Comment by claperle** [comment]
Looks like the logic below can be removed:
![image](https://user-images.githubusercontent.com/92933945/235649833-22a3f079-d888-46f8-bc0e-edef05eb4eca.png)

It does not appear to be used as you pointed out.
