### ISSUE TITLE
Question about 19-21 RDS and schema

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#1116]
I'd like to ask one question about 19-21 RDS and schema.

**Background**
- In the schema, ```thermostat_heating_setpoint_schedule``` key's note says that "If the schedule is not present, the design thermostat heating setpoint is assumed to be constant. Constraint to use when implemented :Schedule:". 

- From [this part of the RDS](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-21.md#:~:text=if%20max(zone_p%2Cthermostat_heating_setpoint_schedule)%20%3E%3D%2060), It says if the max heating setpoint temp schedule is greater than 60 degF, ```serves_zones_heated_to_60_or_higher_in_proposed``` is True. 

**Question** 
When ```thermostat_heating_setpoint_schedule```'s schedule is not defined, what constant value should we set? Or, may I ignore this part and assume the schedule is always present?

**Comment by weilixu** [comment]
In that case, I think we should raise exception and return an undetermined results for the rule.
getattr_ shall do the job.
