### ISSUE TITLE
Question: Section 19-34

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#1184]
The rule assertion in the section [19-34](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-34.md) says:

"It appears that < insert hvac_p.d > is only being simulated in the P_RMI to meet the requirements described in Section G3.1-10 HVAC Systems proposed column c and d for heating and/or cooling. Check that the hvac system fan is simulated to be cycled ON and OFF to meet heating and/or cooling loads during occupied hours as applicable. Note that per the RMD the fan associated with < insert hvac_b.id > is operating as < insert operation_during_occupied_b > during occupied hours. This may require further investigation if only heating or cooling is being simulated to meet Section G3.1-10 HVAC Systems proposed column c or d because different fan operation will be required depending on whether the system is operating in heating or cooling mode."

I would like to alter this message a bit to:

"**It appears that one or multiple zones conditioned by < hvac_b.id > are simulated with virtual heating/cooling HVAC system in the P_RMI to meet the requirements described in Section G3.1-10 HVAC Systems proposed column c and d for heating and/or cooling.** Check that the hvac system fan is simulated to be cycled ON and OFF to meet heating and/or cooling loads during occupied hours as applicable. Note that per the RMD the fan associated with < insert hvac_b.id > is operating as < insert operation_during_occupied_b > during occupied hours. This may require further investigation if only heating or cooling is being simulated to meet Section G3.1-10 HVAC Systems proposed column c or d because different fan operation will be required depending on whether the system is operating in heating or cooling mode."

The issue in the original text was because a pre-assumption that `hvac_p.id` matches `hvac_b.id`. This is not true is many cases. Though the Table 3.1 suggest they could match in the exception c and d, it is still a dangerous assumption programmatically.
Would you agree with the text update?

**Comment by claperle** [comment]
@weilixu I agree with the change.

**Comment by weilixu** [comment]
Completed and implementation and merged the PR.
