### ISSUE TITLE
Missing bpf_building_area_type element and corresponding options in the ASHRAE229.schema file

### ISSUE THREAD

**Issue by JacksonJ-KC** [pnnl/ruleset-checking-tool#1197]
Rule 1-1 and 1-2 involve checking the Output `total_area_weighted_building_performance_factor` against the expected value based on the project climate zone, building area type(s) and their associated area. Building area types are those corresponding to the types listed in ASHRAE 90.1-2019 Table 4.2.1.1. Projects need the ability to specify the building area type to use for the BPF table, especially if the building-area method is _not_ being used to specify lighting.

Proposing a new data element in the BuildingSegments data group `bpf_building_area_type` with options:
MULTIFAMILY,
HEALTHCARE_HOSPITAL,
HOTEL_MOTEL,
OFFICE,
RESTAURANT,
RETAIL,
SCHOOL,
WAREHOUSE,
ALL_OTHER

If this element is not specified in an RMD, a function will attempt to map lighting building area type(s) to BPF building area type(s).
If a project does not use the building-area method of lighting specification, a function will attempt to map lighting space types to BPF building area type(s) and will make an educated guess at the BPF building area type to apply to each building segment - but this may have an UNDETERMINED outcome.

**Comment by JacksonJ-KC** [comment]
@JasonGlazer Yes that would address my biggest concern. Ideally the mapping from space types to BPF building area types would never be used because I feel it introduces too many assumptions in an area that is critical to a project's performance compliance.

**Comment by JasonGlazer** [comment]
Added notes to BuildingSegment.lighting_building_area_type to encourage use even when not using building area method. This was added for 0.0.36 schema update.
