### ISSUE TITLE
Issues with ```get_zone_target_baseline_system``` logic

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#1201]
This case ([link](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/get_zone_target_baseline_system.md#:~:text=zone%5D%5B%22SYSTEM_ORIGIN%22%5D%20%3D%20%22G3_1_1g_part1%22-,else%3A%20else%3A,-change%20the%20system)) in the ```get_zone_target_baseline_system``` function can never occur because 

if [this condition](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/get_zone_target_baseline_system.md#:~:text=if%20the%20zone%20meets%20g3_1_1g%3A%20if%20does_zone_meet_G%3A) is true, it means the ```total_computer_peak_cooling_load``` is greater than 600,000 Btu/hr ([link](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/G311_exceptions/does_zone_meet_G3_1_1g.md#:~:text=check%20if%20the%20peak%20load%20is%20higher%20than%20600%2C000%20btu/hr%20if%20total_computer_peak_cooling_load%20%3E%20600%2C000%20btu/hr%3A%20result%20%3D%20True)). Thus, [the else case](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/get_zone_target_baseline_system.md#:~:text=zone%5D%5B%22SYSTEM_ORIGIN%22%5D%20%3D%20%22G3_1_1g_part1%22-,else%3A%20else%3A,-change%20the%20system) here can't occur at all.

I'd appreciate it if you could let me know how you should move forward. Thanks!

**Comment by weilixu** [comment]
This has been resolved
