### ISSUE TITLE
19-23 occupancy multiplier value

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#1230]
Issue at this [line](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-23.md?plain=1#L60).
Should this be the minimum of above zero value?

**Comment by claperle** [comment]
> Issue at this [line](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-23.md?plain=1#L60). Should this be the minimum of above zero value?

@weilixu I don't think so. The language in App G just says the minimum "For heating sizing runs, schedules for internal loads, including those used for occupants, lighting, gas and electricity using equipment, shall be equal to the lowest hourly value used in the annual simulation run". It doesn't say lowest non zero value so I think zero should be included.

**Comment by weilixu** [comment]
> > Issue at this [line](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-23.md?plain=1#L60). Should this be the minimum of above zero value?
> 
> @weilixu I don't think so. The language in App G just says the minimum "For heating sizing runs, schedules for internal loads, including those used for occupants, lighting, gas and electricity using equipment, shall be equal to the lowest hourly value used in the annual simulation run". It doesn't say lowest non zero value so I think zero should be included.

Ok. My main concern is OA when running sizing. The zones that has OA based on occupancy would not have OA in the case of 0.

**Comment by claperle** [comment]
> > > Issue at this [line](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-23.md?plain=1#L60). Should this be the minimum of above zero value?
> > 
> > 
> > @weilixu I don't think so. The language in App G just says the minimum "For heating sizing runs, schedules for internal loads, including those used for occupants, lighting, gas and electricity using equipment, shall be equal to the lowest hourly value used in the annual simulation run". It doesn't say lowest non zero value so I think zero should be included.
> 
> Ok. @claperle My main concern is OA when running sizing. The zones that have OA based on occupancy would not have OA in the case of 0.

@weilixu hmm, for sizing projects should not assume 0 OA but this is for occupant loads. Hopefully there is a separate way for determining OA used for sizing.

**Comment by weilixu** [comment]
> > > > Issue at this [line](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-23.md?plain=1#L60). Should this be the minimum of above zero value?
> > > 
> > > 
> > > @weilixu I don't think so. The language in App G just says the minimum "For heating sizing runs, schedules for internal loads, including those used for occupants, lighting, gas and electricity using equipment, shall be equal to the lowest hourly value used in the annual simulation run". It doesn't say lowest non zero value so I think zero should be included.
> > 
> > 
> > Ok. @claperle My main concern is OA when running sizing. The zones that have OA based on occupancy would not have OA in the case of 0.
> 
> @weilixu hmm, for sizing projects should not assume 0 OA but this is for occupant loads. Hopefully there is a separate way for determining OA used for sizing.

@claperle I checked with people in the lab, it seems Eplus will use the annual occupancy schedule for sizing. The heating design occupancy schedule is only for occupant loads. So we are fine with 0 occupancy multiplier in this case. Thank!

**Comment by claperle** [comment]
> > > > > Issue at this [line](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-23.md?plain=1#L60). Should this be the minimum of above zero value?
> > > > 
> > > > 
> > > > @weilixu I don't think so. The language in App G just says the minimum "For heating sizing runs, schedules for internal loads, including those used for occupants, lighting, gas and electricity using equipment, shall be equal to the lowest hourly value used in the annual simulation run". It doesn't say lowest non zero value so I think zero should be included.
> > > 
> > > 
> > > Ok. @claperle My main concern is OA when running sizing. The zones that have OA based on occupancy would not have OA in the case of 0.
> > 
> > 
> > @weilixu hmm, for sizing projects should not assume 0 OA but this is for occupant loads. Hopefully there is a separate way for determining OA used for sizing.
> 
> @claperle I checked with people in the lab, it seems Eplus will use the annual occupancy schedule for sizing. The heating design occupancy schedule is only for occupant loads. So we are fine with 0 occupancy multiplier in this case. Thank!

@weilixu Great!
