### ISSUE TITLE
pci equation incorrect

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#1390]
This equation https://github.com/pnnl/ruleset-checking-tool/blob/master/rct229/rulesets/ashrae9012019/section1/section1rule3.py#L115
is incorrect. It is missing a bracket to do the sum first before division.
It will need update both in rule definition @yunjoonjung-PNNL  and test files @jugonzal07

**Comment by yunjoonjung-PNNL** [comment]
Good catch! 

I made this draft PR (#1391). I'd appreciate it if @jugonzal07 could update the testing JSON file in this PR. Thank you!

**Comment by JacksonJ-KC** [comment]
I am currently making updates to the TCD spreadsheet and will make these updates too.

**Comment by JacksonJ-KC** [comment]
I made updates to the rule tests, and I pushed the updated test json for rule 1-3 to https://github.com/pnnl/ruleset-checking-tool/pull/1391
