### ISSUE TITLE
Rule 5-2. Full Evaluation? Applicability Only?

### ISSUE THREAD

**Issue by JacksonJ-KC** [pnnl/ruleset-checking-tool#1442]
> The building shall be modeled so that it does not shade itself

[RDS is written with PASS/FAIL outcomes](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section5/Rule5-2.md) (full evaluation)
Rule in python is written with NOT_APPLICABLE/UNDETERMINED outcomes where:
If the baseline has shading surfaces (seems like it should fail) the outcome is NOT_APPLICABLE.
If the baseline does not have shading surfaces (seems like it should pass) the outcome is UNDETERMINED.

**Comment by weilixu** [comment]
At one point, we decided to put this as a partial evaluation / secondary rule but the RDS did not updated (RCT team translated it).
I think the results is reversed in this rule.
However, after re-reading the RDS, I think it is not clear if the rule only returns not_applicable and undetermined
