### ISSUE TITLE
Rule 22-7 and 22-33 Applicability 

### ISSUE THREAD

**Issue by JacksonJ-KC** [pnnl/ruleset-checking-tool#1454]
When there is a primary loop and no secondary loop I would expect a FAIL outcome, however we are including 'at least one primary/secondary loop' as an applicability check for the rule. 

The test cases that has modeled only a primary loop receives NOT_APPLICABLE instead of FAIL.

See `get_primary_secondary_loops_dict()`

**Comment by claperle** [comment]
@JacksonJ-KC I don't understand the reason for the applicability check. I think it can be removed and would solve the issue you noticed. Do you agree?

**Comment by JacksonJ-KC** [comment]
Agreed
