### ISSUE TITLE
Rule 19-4 manual_check_required()

### ISSUE THREAD

**Issue by JacksonJ-KC** [pnnl/ruleset-checking-tool#1456]
`space_lighting_or_vent_space_type_is_defined` can never be False in the rule implementation because either the lighting space type or the ventilation space type must be defined for the rule to make it past `is_applicable()` so we cannot evaluate True for manual_check_required()`

The RDS case for undetermined says [the lighting or ventilation space type is NOT defined](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-4.md?plain=1#L94) but this code checks if either IS defined `space_lighting_or_vent_space_type_is_defined = space_b.get("lighting_space_type") or space_b.get("ventilation_space_type")`

Then uses `not` in manual_check_required which means both must be undefined.
```
return not space_lighting_or_vent_space_type_is_defined 
and (not is_lighting_bldg_area_defined_b or is_building_area_MF_dormitory_or_hotel_b)
```

**Comment by weilixu** [comment]
#1466 merged. Close this Issue
