### ISSUE TITLE
Rule 15-4 shouldn't depend on order in RMR

### ISSUE THREAD

**Issue by mcneillj** [pnnl/ruleset-checking-tool#16]
Current implementation of Rule 15-4 requires the RMR object ordering to be the same between the user and baseline models.  This rule (and other similar rules) should be able to search the list of objects in the non-indexed RMR for matches.  This would allow for a match regardless of order.

![image](https://user-images.githubusercontent.com/4923674/113901546-cebdfe80-9783-11eb-89ea-f146b4dffe6a.png)

**Comment by charliepnnl** [comment]
The implementation of this rule is changed in an upcoming PR for 15-5 and 15-6.

Also, this code **does not** assume they are in the same order. They are matched up by the `create_context_list()` method of the `RuleDefinitionListBase` class.  This method is automatically called by the `rule_check()` method of `RuleDefinitionListBase` and returns a list of `UserBaselineProposedVals` trios. The elements of that list are each sent to `self.each_rule.evaluate()`
