### ISSUE TITLE
Dev. insert function required_fields (including nested functions) to the rule class required_fields class variable

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#320]
The purpose of this issue is to implement a new mechanism in the rules & functions to form a list of fields that are required for context validity check.
1. #269 shows the example of required fields of a function. We will need to expand the list to include the context info e.g. 
```python
GET_HVAC_ZONE_LSIT_W_AREA_DICT__REQUIRED_FIELDS = 
{
    "building": {
        "building_segments[*].zones[*].spaces[*]": ["floor_area",],
        "building_segments[*].zones[*].terminals[*]": ["served_by_heating_ventilation_air_conditioning_systems"],
    },
    "building_segments":{
        "zones[*].spaces[*]": ["floor_area",],
        "zones[*].terminals[*]": [ "served_by_heating_ventilation_air_conditioning_systems"],
    },
    "zones":{
        "spaces[*]": ["floor_area", ],
        "terminals[*]": ["served_by_heating_ventilation_air_conditioning_systems"],
    },
}
```
2. Insert Required_fields from the nested functions to the above list (need to add mechanism to only save the unique jsonpath).
3. In the rulset, we will add the required fields from the functions to the self.required_fields when initialize the class variables in the constructor. 
    - A new parameter is created that should include a dict of {function_name: function}.
    - A new method in the ruledefintionbase class that extracts the required_fields from functions and add them to the self.requried_fields
   
4. The required_fields in functions & rules shall only be the field that will prevent function/rule definitions to successfully complete at least one logic execution. For example, the "tilt" in the get_opaque_surface_type function.

**Comment by weilixu** [comment]
@charliepnnl could you take a look at the description and let me know if it is accurate as what we discussed?

**Comment by charliepnnl** [comment]
Here is my attempt at putting this all together.

Our central idea is to use jsonpath to specify elements within an RMR and to specify a list of fields that those elements are required to have. We can articulate this pairing in a dictionary as
**Form 1:**  
`{"a json path": [list of required fields], ...}`.

As long as we are working with the entire RMR, the implementation of this idea is quite simple. It gets a bit trickier when we are working within a nested context such as a nested rule definition or nested function calls. As we move through the nested levels, we have to be clear about the context in which each json path is to be evaluated.

 In the nested scenario it can be more helpful to articulate our jsonpath–required fields idea as
**Form 2:**
```
[{"jsonpath_list": [a list of json paths], "required_fields": [list of required fields]}, ...]
```
In this form, we would apply the list of json paths one after another to get the RMR elements. Each path in the list comes from each nested level in turn.

### Rule Definitions
Thankfully, each rule has a well defined, single context in which the json path is evaluated. For a top-level rule, this is either *rmr_context* if specified else it is the whole RMR. For a nested rule this is typically either the *rmr_context* or *list_path* from its parent rule.

A rule, at any level, can have a `required_fields` field that has Form 1 above.

By piecing together the json paths together with the appropirate *rmr_context* or *list_path*, we can always
create a Form 2 list representing the required fields from the whole-RMR perspective.

### Ruleset Functions
A ruleset function `rule_set_fn(param_a, param_b, ...)` can have one or more parameters that represent elements in the RMR structure. We can specify that certain nested-sub-elements within each parameter element have certain fields. To do this, we use a dictionary such as  
**Form 3**:
```
{
  "param_a": {
    "json path into param_a": [list of required fields], ...
  },
  "param_b": {
    "json into param_b": [list of required fields],
    ...
  },
  ...
}
```
As a convenient way of keeping a ruleset function and its required fields together, we can assign the above dictionary to a *required_fields* instance variable for the function with code such as
```
def rule_set_fn(param_a, param_b, ...):
   code goes here

setattr(
  rule_set_fn,
  "required_fields",
  {
    "param_a": {
      "json path into param_a": [list of required fields], ...
    },
    "param_b": {
      "json into param_b": [list of required fields],
      ...
    },
    ...
  }
)
```
#### Ruleset function from a rule
To form the connection to this ruleset function from a rule we can add a *ruleset_functions* field to the rule definition and assign it a list of the following form.  
**Form 4:**
```
[
  {
    "ruleset_function": reference to an imported ruleset function,
    "ruleset_params": {
        "param name": "json path into the rule's context to reach the parameter",
        ...
      },
      ...
  },
  ...
]
```
We can use this list, together with the approprate *rmr_context*, *list_path* values in any parent rules to produce a Form-2 structure that can be used to get the required fields from the RMR level.


#### Ruleset function from another ruleset function
To form the connection to a ruleset function from another ruleset function, we can add a *ruleset_functions* field to the ruleset function object as we did for *required_fields* and assign it a list of the following form.  
**Form 4:**
```
[
  {
    "ruleset_function": reference to an imported ruleset function,
    "ruleset_params": {
      "param name": {
        "caller_context":  "calling function's parameter name",
        "param_path": "json path into caller_context to reach this parameter"
      },
      ...
    }
  },
  ...
]
```
We can use these lists recursively to produce a Form-2 structure that can be used to get the required fields from the RMR level.

**Comment by charliepnnl** [comment]
Actually, here is a slightly simpler Form 4:
```
[
  {
    "ruleset_function": reference to an imported ruleset function,
    "params": [
      {
        "name":  "the parameter name",
        "caller_param":  "calling function's parameter name",
        "path": "json path into caller_param to reach this parameter"
      },
      ...
    ]
  },
  ...
]
```

**Comment by weilixu** [comment]
Thanks for the comments. If I understand correctly, it seems we want to convert each function to a class and each class has ```required_fields``` parameter. The ```rule_set_fn(param_a, param_b...)``` is an abstract method. We also add a ```ruleset_functions``` field in both function class & rule definition class and assigned a list in the *Form 4* format.

**Comment by charliepnnl** [comment]
A standard function is already an object to which we can add instance variables as in the following code I just ran in the python repl. We don't even need to use *setattr* as I sugested above.
```
>>> def ruleset_fn(param_a):
...   pass
... 
>>> ruleset_fn.required_fields = {"param_a": {"jpath": ["foo"]}}
>>> ruleset_fn.required_fields
{'param_a': {'jpath': ['foo']}}
>>> 

```

**Comment by weilixu** [comment]
> A standard function is already an object to which we can add instance variables as in the following code I just ran in the python repl. We don't even need to use _setattr_ as I sugested above.
> 
> ```
> >>> def ruleset_fn(param_a):
> ...   pass
> ... 
> >>> ruleset_fn.required_fields = {"param_a": {"jpath": ["foo"]}}
> >>> ruleset_fn.required_fields
> {'param_a': {'jpath': ['foo']}}
> >>> 
> ```

That is great! Thanks for the clarification. The implementation is straightforward. We should start adding these as soon as we upgrade the schema version.

**Comment by charliepnnl** [comment]
@weilixu  I think we (i) overlooked something important here.  A nested function may be called conditionally. So the required field constraints it imposes may not always be active.  For this reason, I'm not sure it makes sense for us to collect the required field constraints from all the nested ruleset functions.
