### ISSUE TITLE
Zone conditioning category question - Semiheated zones

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#412]
Semi-heated zone might be double-counted under the current logic.

The current logic to identify semi-heated zones:

1. If a zone does not meet directly conditioned criteria but meets for semi-heated zones, put the zone in the semi-heated list [Line 58](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/get_zone_conditioning_category.md?plain=1#L58-L62)
2. If a zone is in the directly conditioned list -> go through indirectly conditioned zone checks, and create an indirectly conditioned zone list.
3. Loop through every zone [Line 90](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/get_zone_conditioning_category.md?plain=1#L90-L109)
    - a zone is in directly conditioned zone or indirectly conditioned zone: residential / non-residential / mixed identification
    - a zone is in the semi-heated zone list - Semi-Heated.
    ...

In the above step 2, one scenario is if a zone is in the semi-heated zone list, it will also go through the indirectly conditioned zone checks and could possibly be identified as an indirectly conditioned zone.

In this case, do we prefer this zone to be identified as an indirectly conditioned zone or a semi-heated zone?

**Comment by xingcx** [comment]
In such case, the zone needs to be identified as indirectly conditioned zone. Indirectly conditioned zones has priority over semi-heated zones.

**Comment by mkarpman** [comment]
I agree.

**Comment by weilixu** [comment]
@xingcx  @mkarpman  Thanks for the confirmation.
