### ISSUE TITLE
Rule check outcome

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#414]
Currently, the rule check outcome has `PASS`, `FAIL`, `UNDETERMINED`, and `UNDETERMINED` covers `manual check required` cases.

The RCT team is working on a number of exception catches and wants to confirm with RDS what outcome we should label for:
1. Rule checking catch missing key exception from functions or rule definitions -> In this case, the outcome should be `FAIL` or `UNDETERMINED`?
2. Rule checking catch data failure exception, for example, the sum of the floor area of a thermal zone  = 0, the outcome should be `FAIL` or `UNDETERMINED`?
3. Other exceptions that will affect software execution but are not part of the RDS logic.

The RCT team also had a discussion to include `status` for each rule in the output template to separate these execution exceptions from the outcomes calculated by RDS logic. We can run through this idea in a team meeting.

**Comment by mkarpman** [comment]
I think our views about possible outcomes have evolved. Here is my take on the current direction:
A. PASS = all data required for the check is provided in the RMR and aligns with the expected logic.
B. FAIL = all data required for the check is provided in the RMR and conflicts with the expected logic.
C. UNDERTERMINED = some or all data required for the check is missing in the RMR OR this is a non-mandatory check that applies to the project but cannot be checked by the RCT.  In either case a manual check will be required.

Based on this logic, I think the outcome for (1) should be UNDERTERMINED (e.g., lighting space type is missing so RDS cannot establish whether the baseline LPD is correct) and for (2) it should be FAIL (data is there but is wrong). I think there was a plan to do an RMR consistency check at the time that it is parsed, and 0 zone area could be a part of this test. I think inconsistent RMRs (e.g., when connection between objects is broken) should be rejected.

**Comment by weilixu** [comment]
Thank you, Maria, the explanation makes sense. I wonder if this has been documented before?

**Comment by mkarpman** [comment]
This is covered in Section 4.3.2.1 of 229P draft language. https://onedrive.live.com/edit.aspx?cid=796769604e905084&page=view&resid=796769604E905084!123&parId=796769604E905084!124&authkey=!ACtFTkgcGDgG1Qk&app=Word

**Comment by mkarpman** [comment]
We have also recently discussed potentially adding another outcome indicating whether RDS applies. This would help articulate the RCT requirements in respect to non-mandatory rules. For such rules, the RCT would be required to do applicability check (and there would be ruleset tests for that) but not to check the actual logic. The RDSs already support this (each has an applicability check). Currently, when a rule doesn't apply, RDS does not produce any outcome at all, which is effectively the fourth possible outcome option (PASS, FAIL, UNDERTERMINED, no outcome)

**Comment by weilixu** [comment]
In that case, we will still need to have some label in the outcome field - I believe it was written as `NOT APPLICABLE` in the [template](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/_rule_template.md?plain=1#L83).
Let me know if that works for now.

**Comment by weilixu** [comment]
As discussed:
1. Fail / Undermined with informative message
2. Whether to distinguish systematic errors from logic errors, and add this part to the Standard?
