### ISSUE TITLE
Compare Schedule issue

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#440]
The ELFH difference is calculated by `ELFH_schedule_1 / ELFH_schedule_2`

There are two scenarios that `elfh_schedule_2 = 0`:
1. mask schedule is 0 - In this case, both `ELFH_schedule_1` and `ELFH_schedule_2` are zero
2. comparison factor is 0 - In this case, `ELFH_schedule_2` is zero.

The PR set `EFLH_difference = ELFH_schedule_1` if `ELFH_schedule_2 = 0` but we also had discussion whether we should raise exception when `ELFH_schedule_2 = 0` as this may seems like a data error.

How should we handle the case for `ELFH_schedule_2 = 0`? Any suggestions?

**Comment by weilixu** [comment]
Discussion:
Decided to change ELFH_difference calculation from division to subtraction.
`elfh_differences = elfh_schedule_1 - elfh_schedule_2`

**Comment by claperle** [comment]
Hi Weili,

I am not familiar with this function as Xing created it. I think she is in
a better position to help.

Christina

*Christina LaPerle* PE, BEMP, CEM, CBCP
Senior Energy Engineer, Associate
________________
[image: image.png]
Phone 860.266.6220
We are always looking for motivated professionals to join our team. See our
career options here <https://karpmanconsulting.net/available-careers>!
