### ISSUE TITLE
5-45 logic

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#454]
In [5-45](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section5/Rule5-45.md), the rule checks whether baseline matches the proposed.

It is recommended to to switch the logic from between line [23-29](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section5/Rule5-45.md?plain=1#L23-L29) to:
`- For each zone in the Baseline model: 'for zone_p in P_RMR...zones:'
   - Get zone infiltration: `infiltration_p = zone_p.infiltration`
   - Get matching zone in B_RMR: `zone_b = match_data_element(B_RMR, Zones, zone_p.id)`
   - ...
`
What do you think?

**Comment by charliepnnl** [comment]
I think you meant `- For each zone in the Proposed model: ...`

**Comment by xingcx** [comment]
I'm thinking if the rule is applicable to B_RMR, it should check B_RMR elements as P_RMR is the reference?
`**Applicability:** All required data elements exist for B_RMR`.

**Comment by charliepnnl** [comment]
I think Xing is correct. The RDS says that the proposed matches the baseline. So we should index on the baseline as the RDS logic shows.

**Comment by weilixu** [comment]
> I'm thinking if the rule is applicable to B_RMR, it should check B_RMR elements as P_RMR is the reference?
> `**Applicability:** All required data elements exist for B_RMR`.

The standard language is often phrased as the baseline should match the proposed model, which got me wondering why we are doing it the other way.

**Comment by xingcx** [comment]
That is correct. The baseline should match the proposed model. If we are checking the baseline (whether the baseline matches the proposed), I assume we should loop through the baseline model instead of the proposed?

**Comment by weilixu** [comment]
> That is correct. The baseline should match the proposed model. If we are checking the baseline (whether the baseline matches the proposed), I assume we should loop through the baseline model instead of the proposed?


I think the final rule check outcome is the same. The difference could be in the report.

Thinking a case where:
b_rmr contains {surface_1, surface_2}
p_rmr contains {surface_2, surface_4}

Loop b_rmr and try to find a matched p_rmr will raise error on no matching of surface_1
Loop p_rmr and try to find a matched p_rmr will raise error on no matching of surface_4

Both lead to a fail result, but reporting msgs are different.

**Comment by mkarpman** [comment]
I am a little confused... based on the [TCD Master](https://onedrive.live.com/edit.aspx?cid=796769604e905084&page=view&resid=796769604E905084!386&parId=796769604E905084!358&authkey=!ACtFTkgcGDgG1Qk&app=Excel) 5-45 checks that "The  infiltration modeling method in the baseline includes adjustment for weather and building operation". It doesn't check rates.
