### ISSUE TITLE
Section 6 rule 13 & normalized schedule

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#473]
6-13
[RDS](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section6/Rule6-13.md?plain=1#L41) has `adjusted_reduction_factor_p `. Should we assume this to be 1.0?

[Line 15](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section6/Rule6-13.md?plain=1#L45-L49):  We probably need to update the assertions because the returned results from `compare_schedule` are not `Match` or `EQUAL AND LESS`.

normalize_space_schedules
[Line 37](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/normalize_space_schedules.md?plain=1#L37) It is a bit misleading in the RDS that `interior_lighting.lighting_multiplier_schedule` does not return a `schedule` but a `schedule_id`. Do we need to update this part?

**Comment by supriyagoel** [comment]
@weilixu I believe the term 'adjusted_reduction_factor' in 6-8 should be renamed 'comparison_factor' as is used as an input to the compare schedules function.
https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section6/Rule6-8.md
<img width="730" alt="image" src="https://user-images.githubusercontent.com/8323384/172769109-4499dab2-0ad2-4dfa-83db-54e730917b2c.png">

If I understand the function to normalize space schedules correctly, if occupancy control credit is the only credit applied, it should result in normalized schedules for B and P which are the same, hence if compare schedule function would verify the same assuming a comparison factor of 1.

Hope I'm thinking of this correctly- you've already implemented the the normalize space schedule function, do you agree that it would result in the same sch for B and P if occupancy control credit is the only credit applied to the P?
