### ISSUE TITLE
Rename normalize_space_schedules function?

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/ruleset-checking-tool#478]
The normalize_space_schedules function was originally intended to be a general-purpose function for normalizing space schedules. However, it has turned out to be very specific to interior_lighting.

Proposal:  Rename as `normalize_space_interior_lighting_schedule` or `normalize_interior_lighting_schedule`.

**Comment by mkarpman** [comment]
We discussed this at the call yesterday and changing the name sounds good.
