### ISSUE TITLE
Intend of interior_lighting_u.are_schedules_used_for_modeling_daylighting_control in Rule6-7 RDS

### ISSUE THREAD

**Issue by charliepnnl** [pnnl/ruleset-checking-tool#567]
The term *interior_lighting_u.are_schedules_used_for_modeling_daylighting_control* appears in Rule Assertion Cases 1 and 2 of Rule6-7 (see https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section6/Rule6-7.md).  It is not clear what the intent is for this term. 

Each Rule Assertion Case is at the *Zone* level, but *interior_lighting_u.are_schedules_used_for_modeling_daylighting_control* is at the Space level. Should this be interpretted as `all(interior_lighting_u.are_schedules_used_for_modeling_daylighting_control)` in the zone are true, or should it be any?  Note that in Case 1, this term is preceded by "NOT".  So is Case 1 not any, or not all, or something else?

**Comment by mkarpman** [comment]
Good catch! I agree that RDS is not clear about this. I think the part shown below in bold font should be added:

For each space in zone: space_u in zone_u.spaces:

Get interior_lighting in space: interior_lighting_u = space_u.interior_lighting

Check if any interior_lighting has daylight control: if ( lighting.daylighting_control_type != "NONE" for lighting in interior_lighting_u ): has_daylight_control_flag == TRUE

**Check if any interior_lighting with daylight control has it modeled using schedule adjustment: if ( lighting.are_schedules_used_for_modeling_daylighting_control=TRUE for lighting in interior_lighting_u ): daylight_schedule_adjustment_flag == TRUE**

So case 1 applies when there are interior lighting objects that have daylighting controls and neither of them are modeled via schedule adjustment. Case 2 applies when there are interior lighting objects that have daylighting controls and at least one of them is modeled via schedule adjustment. 

I would consider updating the messages as follows:
Case 1: "SOME OF THE SPACES IN ZONE ARE MODELED WITH WINDOW(S) AND/OR SKYLIGHT(S) AND HAVE DAYLIGHTING CONTROLS MODELED EXPLICITLY IN THE SIMULATION TOOL. VERIFY THAT THE MANDATORY LIGHTING CONTROL REQUIREMENTS ARE MET."

Case 2: "SOME OF THE SPACES IN ZONE ARE MODELED WITH WINDOW(S) AND/OR SKYLIGHT(S) AND HAVE DAYLIGHTING CONTROLS MODELED VIA SCHEDULE ADJUSTMENT. VERIFY THAT THE MANDATORY LIGHTING CONTROL REQUIREMENTS ARE MET, AND THAT THE SUPPORTING DOCUMENTATION IS PROVIDED FOR THE SCHEDULE ADJUSTMENT ."

**Comment by weilixu** [comment]
> Good catch! I agree that RDS is not clear about this. I think the part shown below in bold font should be added:
> 
> For each space in zone: space_u in zone_u.spaces:
> 
> Get interior_lighting in space: interior_lighting_u = space_u.interior_lighting
> 
> Check if any interior_lighting has daylight control: if ( lighting.daylighting_control_type != "NONE" for lighting in interior_lighting_u ): has_daylight_control_flag == TRUE
> 
> **Check if any interior_lighting with daylight control has it modeled using schedule adjustment: if ( lighting.are_schedules_used_for_modeling_daylighting_control=TRUE for lighting in interior_lighting_u ): daylight_schedule_adjustment_flag == TRUE**
> 
> So case 1 applies when there are interior lighting objects that have daylighting controls and neither of them are modeled via schedule adjustment. Case 2 applies when there are interior lighting objects that have daylighting controls and at least one of them is modeled via schedule adjustment.
> 
> I would consider updating the messages as follows: Case 1: "SOME OF THE SPACES IN ZONE ARE MODELED WITH WINDOW(S) AND/OR SKYLIGHT(S) AND HAVE DAYLIGHTING CONTROLS MODELED EXPLICITLY IN THE SIMULATION TOOL. VERIFY THAT THE MANDATORY LIGHTING CONTROL REQUIREMENTS ARE MET."
> 
> Case 2: "SOME OF THE SPACES IN ZONE ARE MODELED WITH WINDOW(S) AND/OR SKYLIGHT(S) AND HAVE DAYLIGHTING CONTROLS MODELED VIA SCHEDULE ADJUSTMENT. VERIFY THAT THE MANDATORY LIGHTING CONTROL REQUIREMENTS ARE MET, AND THAT THE SUPPORTING DOCUMENTATION IS PROVIDED FOR THE SCHEDULE ADJUSTMENT ."

Thanks Maria! @charliepnnl I will update the RDS and could you update the code in 6-7 so it is ready for merge?

**Comment by yunjoonjung-PNNL** [comment]
> Good catch! I agree that RDS is not clear about this. I think the part shown below in bold font should be added:
> 
> For each space in zone: space_u in zone_u.spaces:
> 
> Get interior_lighting in space: interior_lighting_u = space_u.interior_lighting
> 
> Check if any interior_lighting has daylight control: if ( lighting.daylighting_control_type != "NONE" for lighting in interior_lighting_u ): has_daylight_control_flag == TRUE
> 
> **Check if any interior_lighting with daylight control has it modeled using schedule adjustment: if ( lighting.are_schedules_used_for_modeling_daylighting_control=TRUE for lighting in interior_lighting_u ): daylight_schedule_adjustment_flag == TRUE**
> 
> So case 1 applies when there are interior lighting objects that have daylighting controls and neither of them are modeled via schedule adjustment. Case 2 applies when there are interior lighting objects that have daylighting controls and at least one of them is modeled via schedule adjustment.
> 
> I would consider updating the messages as follows: Case 1: "SOME OF THE SPACES IN ZONE ARE MODELED WITH WINDOW(S) AND/OR SKYLIGHT(S) AND HAVE DAYLIGHTING CONTROLS MODELED EXPLICITLY IN THE SIMULATION TOOL. VERIFY THAT THE MANDATORY LIGHTING CONTROL REQUIREMENTS ARE MET."
> 
> Case 2: "SOME OF THE SPACES IN ZONE ARE MODELED WITH WINDOW(S) AND/OR SKYLIGHT(S) AND HAVE DAYLIGHTING CONTROLS MODELED VIA SCHEDULE ADJUSTMENT. VERIFY THAT THE MANDATORY LIGHTING CONTROL REQUIREMENTS ARE MET, AND THAT THE SUPPORTING DOCUMENTATION IS PROVIDED FOR THE SCHEDULE ADJUSTMENT ."

@mkarpman Thank you so much for this kind explanation. I have one question. Is this rule for ```proposed``` or ```user```? The reason why I ask this is that before the RDS was updated, it was about the ```proposed``` design. Also, in the updated RDS, in **Appendix G Section Reference** section it says it's about the ```proposed``` and **Rule Logic** describes this rule in ```proposed``` design manner.

**Comment by mkarpman** [comment]
Another great question! The rule checks for two things: (1) whether mandatory daylighting controls are met by the project (which is a U-RMR test) and (2) whether an appropriate schedule adjustment methodology is used for daylighting controls that are modeled vis schedule adjustment.  Logically, the first check is for U-RMR and the second check is for P-RMR. But the bottom line is that it doesn't really matter whether we check U or P-RMR because for "are_schedules_used..." field  "AppG P_RMD Equals U_RMD: True", so the rule will produce the same outcome whether it is applied to U or P RMR. I recommend sticking with U-RMR, which reflect the current RDS implementation. If @supriyagoel is on board, I'll update the Rules spreadsheet https://onedrive.live.com/edit.aspx?cid=796769604e905084&page=view&resid=796769604E905084!423&parId=796769604E905084!212&authkey=!ACtFTkgcGDgG1Qk&app=Excel the rule 6=7 accordingly because currently it suggests that it is based on the proposed design. But whatever is easier will do.

**Comment by supriyagoel** [comment]
@mkarpman I believe our strategy has been to verify rule application for P RMR and not U RMR. Would it be better to follow that strategy and verify this rule on the P RMR as well? 
We need not update the RDS if easier- its not normative so doesn't have to be consistent. 

If we decide to apply this rule to U RMR then the rule test needs to be updated and we should probably update all other rule tests to apply to U RMR as well instead of P RMR.

**Comment by mkarpman** [comment]
If it's easier to keep it as P_RMR test, then so be it. As I mentioned, the outcome would be the same either was since the umrella check requires that P_RMR=U_RMR for this attribute.

**Comment by yunjoonjung-PNNL** [comment]
I appreciate the replies. I will update the 6-5 RDS and Python code accordingly.
