### ISSUE TITLE
Change to Transformer TCD Diagram

### ISSUE THREAD

**Issue by mcneillj** [pnnl/ruleset-checking-tool#6]
![110997374-4d717880-834b-11eb-9d86-527aa64c421c](https://user-images.githubusercontent.com/4923674/111000406-db8f3400-8336-11eb-8c3a-57f630567cf6.png)

**Comment by mmtillouPNNL** [comment]
![image](https://user-images.githubusercontent.com/80537094/111000885-da6b0080-8350-11eb-8a14-63fe0dcc1239.png)
