### ISSUE TITLE
21-6 logic confirmation

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#604]
Rule 21-6 is [under-development](https://github.com/pnnl/ruleset-checking-tool/pull/591) and the RCT has a question on the assertion condition that needs to be confirmed.

Case 1 assertion:
`if ( boiler_1.operation_lower_limit == 0 ) AND ( boiler_1.operation_upper_limit == boiler_1.rated_capacity ) AND ( boiler_2.operation_lower_limit == boiler_2.rated_capacity ) AND ( boiler_2.operation_upper_limit == boiler_2.rated_capacity * 2 ): PASS`

Though standard says both boilers shall be equally sized, will it be more intuitive to rewrite this to:
`if ( boiler_1.operation_lower_limit == 0 ) AND ( boiler_1.operation_upper_limit == boiler_1.rated_capacity ) AND ( boiler_2.operation_lower_limit == boiler_1.rated_capacity ) AND ( boiler_2.operation_upper_limit == boiler_1.rated_capacity + boiler_2.rated_capacity): PASS`

**Comment by supriyagoel** [comment]
@weilixu and @mkarpman I agree with the suggested approach. Is there somewhere that we're checking that boiler 1 rated capacity = boiler 2 rated capacity?
If not, we should add that before we make this change

**Comment by weilixu** [comment]
Revise the RDS logic to:

`if ( boiler_1.operation_lower_limit == 0 ) AND ( boiler_1.operation_upper_limit == boiler_1.rated_capacity ) AND ( boiler_2.operation_lower_limit == boiler_1.rated_capacity ) AND ( boiler_2.operation_upper_limit == boiler_1.rated_capacity + boiler_2.rated_capacity): PASS`
