### ISSUE TITLE
6-2 logic

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#605]
Rule 6-2 seems have repeated logic
[Applicability check](https://github.com/pnnl/ruleset-checking-tool/blob/626c9f91816cc0751e781d515e26c1ff22b08aad/docs/section6/Rule6-2.md?plain=1#L14): Building has Hotel/Model Guestroom or Dormitory Living Quarters, Dwelling Units space types  

[IF-ELSE statement](https://github.com/pnnl/ruleset-checking-tool/blob/626c9f91816cc0751e781d515e26c1ff22b08aad/docs/section6/Rule6-2.md?plain=1#L28): ```if ( space_p.lighting_space_type == "Guest Room" ) OR ( space_p.lighting_space_type == "Dormitory Living Quarters" ) OR ( space_p.lighting_space_type == "Dwelling Units" ):``` 

The applicability check seems doing the same thing by looping through spaces to check `space_p.lighting_space_type = [GEUST ROOM, DORMITORY LIVING QUARTERS, DWELLING UNITS]`.

Could we condense the repeated logic into one?

**Comment by mkarpman** [comment]
I agree. I think we can remove applicability check and just make it one of the outcomes, so that the RCT outcomes are "Pass", "Fail", "Manual Review" or "Not Applicable". Does it make sense?

**Comment by weilixu** [comment]
> I agree. I think we can remove applicability check and just make it one of the outcomes, so that the RCT outcomes are "Pass", "Fail", "Manual Review" or "Not Applicable". Does it make sense?

Thanks Maria. I think that make sense.
I do have a follow up question:
What should we do with data group that is not meeting the selection criteria. It is happening in some places in the rules and I think there will be more coming up.
We can use 6-2 as an example:

```python
for space in zone.spaces:
    if space.lighting_space_type in [GEUST ROOM, DORMITORY LIVING QUARTERS, DWELLING UNITS]:
        do rulecheck and return PASS, FAIL and UNDETERMINED.
```

What about the `spaces` that do not fall into the selection criteria?
1. We can set them to `Not Applicable` in the outcome.
2. We just ignore them and skip the rule checking.

Issue with Option 1: is when we summarized the component-level rule assertions to calculate the rule-level assertion, it will require customized logic for each rule that RCT currently do not have (e.g. in 6-2 we could ignore all `NOT_APPLICABLE` at component-level results). - This is difficult to implement.

Issue with Option 2: we may end up with no checking in a rule at all (assume an RMD has no space fall into the three space types). We can add a rule-level logic that if there nothing checked then rule-level outcome is "Not Applicable" - this is much easier to implement.

**Comment by mkarpman** [comment]
Weily, I think Option 2 with the rule-level "Not Applicable" outcome makes sense. Perhaps you can bring it up at the RDS call today.

**Comment by weilixu** [comment]
> Weily, I think Option 2 with the rule-level "Not Applicable" outcome makes sense. Perhaps you can bring it up at the RDS call today.

That is great. Thanks!

**Comment by weilixu** [comment]
The discussion agreed that we will use not applicable to label the spaces.
