### ISSUE TITLE
Logic for does_each_zone_have_only_one_terminal

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#627]
RDS [link](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/baseline_systems/baseline_hvac_sub_functions/does_each_zone_have_only_one_terminal.md)

In the description, the function says:

Returns TRUE if each zone input to this function only has one terminal unit. It returns FALSE if any zone **has more than one terminal unit**.

In the rule assertion logic, it states:

check if there is more than one terminal **or no terminal units associated with the zone**:

The question is, when a zone has no terminal associate: 
```python 
zone.terminals is None or len(zone.terminals == 0)
```
, should the function return `True` or `False`?

**Comment by claperle** [comment]
@weilixu @mkarpman I agree with Weili's suggestion. Maria, do you?

**Comment by mkarpman** [comment]
Yes, I agree.
