### ISSUE TITLE
Question - component exist in baseline but not in the proposed

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#654]
I've been playing around RCT using RMDs provided by Jason.

One question I found is the checking component in baseline but cannot found in proposed. It sounds intuitive but there is a special case for that.

For example:
In small office building, the CORE_ZN has no infiltration data group in the proposed model.
However, it has infiltration data group in baseline model with a value of 0.0.
```json
"infiltration": {
                    "id": "CORE_ZN INFILTRATION",
                    "modeling_method": "WEATHER_DRIVEN",
                    "algorithm_name": "ZoneInfiltration",
                    "infiltration_flow_rate": 0.0,
                    "multiplier_schedule": "ALWAYS ON DISCRETE"
                  },
```

In terms of simulation, this is not wrong - basically it means no air leakage to the CORE_ZN. However, the RCT failed the checking due to no match.

We may see this a lot as everyone is trying their own way to automate the baseline. My main questions are:
1. Do we have an agreement on a `PASS` for this case or a `FAILED`?
2. Do we want to add a layer of logic check for this situation in engine or rule definition (RDS might need to be updated)

**Comment by mkarpman** [comment]
I think we should expect certain consistency in how RMDs are generated which may be enforced via RMD tests. So in this example, I would flag missing infiltration component as FAIL.

**Comment by JasonGlazer** [comment]
We are going to find this is very common when we get to HVAC but for building loads it is a little trickier. For this particular case, the missing Infiltration data group and one with a zero flow rate are equivalent but that may not always be the case. 

BTW, for EnergyPlus, this approach is actually quite consistent and I'm not sure we want to be creating infiltration data groups if no infiltration is specified int he input file and reported.

**Comment by weilixu** [comment]
I agree with Jason that this approach in Eplus is quite consistent and we may see more of such behavior happens - some are OK (this particular case), and some are wrong (if the value is over 0.0 in this case).

It is a difficult call as enforcing one-to-one exact match will adds lots of work at software side, and relaxing on this requirement could mean that RCT could produce FAIL for many such cases - which does not necessary means failed.

**Comment by weilixu** [comment]
1. Loads - mark component missing as failed ( RMD tests will QA the load data group).
2. HVAC - skip
