### ISSUE TITLE
Issue with temperature using "pint" package

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#669]
There is an issue with the temperature part in our code. For instance, when we compare two temperatures we have to convert them to Kelvin units to prevent the error.

One potential solution would be to update [this part](https://github.com/pnnl/ruleset-checking-tool/blob/develop/rct229/schema/schema_utils.py#:~:text=pint_qty%20%3D%20number_rmr_item_match.value%20*%20config.ureg(pint_unit_str)) in our source code by putting the ```number_rmr_item_match.value``` variable into ```ureg``` parentheses after converting to string .

**Comment by charliepnnl** [comment]
I'd like to discuss this further sometime soon.
