### ISSUE TITLE
22-20 RDS, minimum_reset_temperature key doesn't exist in the schema

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#685]
1. I believe Rule 22-20 RDS ([LINK](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section22/Rule22-20.md#:~:text=if%20tower_b.minimum_reset_temperature)) should be updated because the G3.1.3.11 section does not describe the condenser water reset but leaving water temperature. More specifically, the section says "_The tower shall be controlled to maintain a leaving water temperature, where weather permits, per Table G3.1.3.11, floating up to the design leaving water temperature for the cooling tower._"

2. Should the ```minimum_reset_temperature``` key be changed to ```leaving_water_setpoint_temperature``` to reflect on what the section says?

**Comment by weilixu** [comment]
This has been addressed in the latest schema. Before updating RCT schema version, we can temporarily modify the schema for the rule definition. Closing the issue.
