### ISSUE TITLE
approach, range, and design_wetbulb_temperature units in the schema

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#691]
Hello Jason,

We believe that the unit of the ```approach```, ```range``` and ```design_wetbulb_temperature``` keys under the ```heat_rejections``` in the schema shall be Kelvin (K) instead of deg C because each of these represents temperature differences. 

Could you confirm this? If this makes sense to you, could you reflect on this to the next version of the schema?

**Comment by yunjoonjung-PNNL** [comment]
Thank you so much Jason!

**Comment by weilixu** [comment]
@yunjoonjung-PNNL @JasonGlazer 
I am unsure whether the `design_wetbulb_temperature` shall be`kelvin` but agree with `approach` and `range`.

**Comment by JasonGlazer** [comment]
I agree, just range and approach should be in K. 

design_wetbulb_temperature should be in C
