### ISSUE TITLE
22-22 RDS clarification question

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#698]
I'd like to ask a few questions about the 22-22 RDS.

1. In the ```Table G3.5.3``` in the 90.1, there is no >= 600 tons case but, [the RDS](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section22/Rule22-22.md#:~:text=else%3A%20size_category%20%3D%20%22%3E%20600TONS%22) has this case. Shouldn't the > 600 tons part be removed in the RDS as it doesn't exist in the table?

2. In terms of the ```table_G3_5_3``` lookup table function, it seems like using the numeric argument instead of string one (e.g., "< 150TONS", ">= 150TONS AND < 300TONS",  etc.) is a better way to be consistent throughout the project.  
How about we input actual chiller rated capacity quantity to the table function? Is this suggestion acceptable to the RDS team?

**Comment by KarenWGard** [comment]
Hi - I am not the one who wrote this function, but I will do my best to work with you to resolve this.

1.  I do not see any categories past >= 300 tons in G3.5.3.  - thoughts @JasonGlazer, @mkarpman ?
2.  yes, a numerical lookup makes sense to me

**Comment by JasonGlazer** [comment]
There are no categories past >=300 tons in Table G33.5.3. Is it possible that the same lookup is used for Table G3.1.3.7? That one does go to >=600 tons.

**Comment by weilixu** [comment]
@JasonGlazer it is possible. By the definition of G3.1.3.7, in baseline, no single chiller shall have capacity that is greater than 800 tons.
I wonder if 22-22 also checks the maximum chiller tons? If that is the case, I think there should be a separate rule to check the limitation.
Adding Maria to this discussion @mkarpman

**Comment by mkarpman** [comment]
The 22-22 RDS is for the following rule: "The baseline building design’s chiller plant shall be modeled with chillers having the type as indicated in Table G3.1.3.7 as a function of building peak cooling load." So the RDS needs only Table 3.1.3.7 which dows have >600 tons bracket.  Table G3.5.3 is not relevant to this RDS.

**Comment by weilixu** [comment]
> The 22-22 RDS is for the following rule: "The baseline building design’s chiller plant shall be modeled with chillers having the type as indicated in Table G3.1.3.7 as a function of building peak cooling load." So the RDS needs only Table 3.1.3.7 which dows have >600 tons bracket. Table G3.5.3 is not relevant to this RDS.

It seems the rule number is renumbered to 22-23 but the question remains for the rule: `The baseline chiller efficiencies shall be modeled at the minimum efficiency levels for full load, in accordance with Tables G3.5.3.`

**Comment by weilixu** [comment]
@yunjoonjung-PNNL 
22 shall remove 600 tons logic. I updated the 22 RDS in the develop branch for development.

Closing the issue now.
