### ISSUE TITLE
```is_there_only_one_hvac_sys_heating_system``` RDS

### ISSUE THREAD

**Issue by yunjoonjung-PNNL** [pnnl/ruleset-checking-tool#832]
It seems like ```is_there_only_one_hvac_sys_heating_system``` function RDS is missing. It's one of the required functions for ```is_baseline_system_9```, as shown [HERE](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/ruleset_functions/baseline_systems/is_baseline_system_9.md#:~:text=carry%20on%3A%20if-,is_there_only_one_hvac_sys_heating_system,-(B_RMR%2C%20hvac_b.id)).

If the RDS already exists, could you direct me to where it's located? 
Thanks!

**Comment by KarenWGard** [comment]
it seems that the function was written.  It can be viewed here
<https://github.com/pnnl/ruleset-checking-tool/blob/RS/WX/is_there_only_one_hvac_sys_heating_system/docs/ruleset_functions/baseline_systems/baseline_hvac_sub_functions/is_there_only_one_hvac_sys_heating_system.md>.
The logic used is len(hvac_b.heating_system)

But Weili closed the pull request saying it is not needed
<https://github.com/pnnl/ruleset-checking-tool/pull/607>

In the current version of the schema
<https://github.com/open229/ruleset-model-description-schema/blob/master/docs229/ASHRAE229.schema.md#heatingventilatingairconditioningsystem>,
it appears that hvac.heating_system returns only one HeatingSystem object,
so there will always only be one (or potentially 0) heating system(s).

**Comment by yunjoonjung-PNNL** [comment]
Thanks for this explanation, Karen! Since this issue is resolved, I'll close it.

**Comment by KarenWGard** [comment]
You’re welcome. Any time.
