### ISSUE TITLE
22-36 in RDS

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#981]
The [22-36](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section22/Rule22-36.md) is created a year ago, and the rule description is 
**Baseline chilled water system that does not use purchased chilled water shall be modeled with constant flow primary loop and variable flow secondary loop.**

The rule conflicts with several other rules, e.g. [22-24](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section22/Rule22-24.md) and [22-8](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section22/Rule22-8.md).

Cross-checking the rule table, it appears the 22-36 rule shall be secondary rule with a description of "Baseline systems served by purchased chilled water shall be modeled with a chilled water distribution pump".

It is a reminder that this RDS needs to be redeveloped into a secondary rule RDS as well as rule definition.

**Comment by KarenWGard** [comment]
Weili,

In the chiller spreadsheet
<https://onedrive.live.com/edit.aspx?resid=796769604E905084!1505&cid=796769604e905084&CT=1677161109229&OR=ItemsView>,
the rule is marked as non-mandatory and the rule description for 22-36
reads:  "Baseline systems served by purchased chilled water shall be
modeled with a chilled water distribution pump"

I have not yet written / reviewed the RDSs for section 22 non-mandatory
rules, but will be working on this this week.

Thanks,

Karen

**Comment by weilixu** [comment]
This is resolved after a clean up effort in the TCD spreadsheet
